drop table if exists chat_message cascade;
drop table if exists chat_user cascade;
drop sequence if exists chat_message_seq;
create sequence chat_message_seq start with 1 increment by 50;
create table chat_message
(
    created_date timestamp(6),
    id           bigint not null,
    content      varchar(255),
    sender       varchar(255),
    primary key (id)
);
create table chat_user
(
    id       bigint generated by default as identity,
    email    varchar(255),
    name     varchar(255) unique,
    password varchar(255),
    primary key (id)
);

insert into chat_user (email, name, password, id)
values ('john@gmail.com', 'john', 'pass', default);
insert into chat_user (email, name, password, id)
values ('nick@gmail.com', 'nick', 'word', default);